version: '3.8'

services:
  database:
    image: bitnami/mariadb:latest
    container_name: "backend_mariadb"
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_USER=$MARIADB_ROOT_USER
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
    ports:
      - $MARIADB_LOCAL_PORT:$MARIADB_DOCKER_PORT
    volumes:
      - "mariadb-data:/bitnami/mariadb"
      - "./backend/src/main/resources/script/init.sql:/docker-entrypoint-initdb.d/init.sql"


  storage:
    image: bitnami/minio:latest
    container_name: "backend_minio"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'media:/data'
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_USER
  
  app:
    container_name: "backend"
    depends_on:
      - database
      - storage
    restart: on-failure
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "app.datasource.backend.url" : "jdbc:mariadb://database:3306/backend",
        "spring.profiles.active" : "prod"
      }'
    volumes:
      - .m2:/root/.m2
    build: ./backend
    stdin_open: true
    tty: true

volumes:
    mariadb-data:
    .m2:
    media:
      driver: local
