version: '3.3'

services:
  database:
    image: bitnami/mariadb:latest
    container_name: "backend_mariadb"
    restart: "always"
    environment:
      - "MARIADB_ROOT_USER=admin" 
      - "MARIADB_ROOT_PASSWORD=admin"
    ports:
      - "3306:3306"
    volumes:
      - "mariadb-data:/var/lib/mysql"
      - "mariadb-etc:/etc/mysql/conf.d"

  storage:
    image: bitnami/minio:latest
    container_name: backend_minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'media:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

volumes:
    mariadb-data:
    mariadb-etc:
    media:
      driver: local
