version: '3.3'

services:
    backend:
        build: 
            context: ./backend
            dockerfile: dockerfile
        volumes:
            - ./backend:/backend
        ports: 
            - 8080:8080
        depends_on:
            - database
            - redis
    database:
        image: 
        environment:
        volumes:
        ports:
    redis:
        image: redis
        volumes:
            - redis_data:/data
volumes:
