version: '3.8'

services:
  database:
    image: bitnami/mariadb:latest
    container_name: "backend_mariadb"
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_USER=$MARIADB_ROOT_USER
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
    ports:
      - $MARIADB_LOCAL_PORT:$MARIADB_DOCKER_PORT
    volumes:
      - "mariadb-data:/bitnami/mariadb"
      - "./backend/src/main/resources/script/init.sql:/docker-entrypoint-initdb.d/init.sql"

  storage:
    image: bitnami/minio:latest
    container_name: "backend_minio"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'media:/data'
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_USER

  model:
    image: model:v1
    container_name: "model"
    build: ./backend-model
    restart: on-failure
    ports:
      - $MODEL_LOCAL_PORT:$MODEL_DOCKER_PORT
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=$MODEL_DOCKER_PORT
      - DEBUG=$MODEL_ISDEBUG

  # To update code inside container, run 
  # >> docker-compose -f... down && docker-compose -f... build app && docker-compose -f... up
  app:
    image: backend:v1
    container_name: "backend"
    build: ./backend
    restart: on-failure
    depends_on:
      - database
      - storage
      - model
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
       "spring.profiles.active" : "dev",
       "app.datasource.backend.url" : "jdbc:mariadb://database:$MARIADB_DOCKER_PORT/backend",
       "spring.application.domain" : "http://app:$SPRING_LOCAL_PORT",
       "app.minio.url" : "http://storage:9000",
       "kdc-model.host" : "http://model:$MODEL_LOCAL_PORT"
      }'
    volumes:
      - ./backend/src:/src
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  mariadb-data:
  .m2:
  media:
    driver: local
