version: '3.8'

services:
  database:
    image: bitnami/mariadb:latest
    container_name: "backend_mariadb"
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_USER=$MARIADB_ROOT_USER
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
    ports:
      - $MARIADB_LOCAL_PORT:$MARIADB_DOCKER_PORT
    volumes:
      - "mariadb-data:/bitnami/mariadb"
      - "./backend/src/main/resources/script/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - backend

  storage:
    image: bitnami/minio:latest
    container_name: "backend_minio"
    restart: unless-stopped
    ports:
      - '0.0.0.0:9000:9000'
      - '0.0.0.0:9001:9001'
    volumes:
      - 'media:/data'
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_USER
    networks:
      - backend

  model:
    image: model:v1
    container_name: "model"
    build: ./backend-model
    restart: on-failure
    ports:
      - $MODEL_LOCAL_PORT:$MODEL_DOCKER_PORT
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=$MODEL_DOCKER_PORT
      - DEBUG=$MODEL_ISDEBUG
    networks:
      - backend
  
  app-client:
    container_name: "client"
    build:
      context: ./frontend 
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_ORIGIN: https://$BACKEND_ORIGIN/backend/api/v1/
        REACT_APP_ENV: $REACT_APP_ENV
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend 
  
  app-server:
    container_name: "backend"
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
      - storage
      - model
    restart: on-failure
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      ENV: $SPRING_ENV
      MARIADB_HOST: database
      MARIADB_PORT: $MARIADB_DOCKER_PORT
      MARIADB_DB: backend
      MARIADB_USERNAME: $MARIADB_ROOT_USER
      MARIADB_PASSWORD: $MARIADB_ROOT_PASSWORD
      MINIO_HOST: storage
      MINIO_PORT: 9000
      MINIO_ACCESS: $MINIO_ROOT_USER
      MINIO_KEY: $MINIO_ROOT_PASSWORD
      MINIO_BUCKET: $MINIO_BUCKET
      JWT_SECRET: $JWT_SECRET
      CLIENT_PATH: $CLIENT_PATH
      EMAIL_USERNAME: $EMAIL_USERNAME
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      KDC_HOST: model
      KDC_PORT: $MODEL_DOCKER_PORT
      APP_HOST: $BACKEND_ORIGIN
      APP_PORT: $SPRING_DOCKER_PORT
    networks: 
      - backend
      - frontend

volumes:
    mariadb-data:
    media:
      driver: local

networks:
  backend:
  frontend: 
