name: ME2DIAG CI/CD
on:
  push:
    branches:
      - master
jobs:
  me2diag_ci_cd:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose --env-file /home/ubuntu/.env -f docker-compose.prod.yml down
      - run: docker-compose --env-file /home/ubuntu/.env -f docker-compose.prod.yml up --build -d